### ISSUE TITLE
Убрать хардкод из bootstrap.yml

### ISSUE THREAD

**Issue by loktionovam** [loktionovam/search_engine_infra#27]
Нужно параметризовать версии утилит в bootstrap.yml, т.е. вместо

```yaml
    - name: Download and install kubectl 1.12.0
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/v1.12.0/bin/linux/amd64/kubectl
        dest: /usr/local/bin/
        mode: 0755
      become: true

```

должно быть

```yaml
    - name: Download and install kubectl {{ kubectl_version }}
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl
        dest: /usr/local/bin/
        mode: 0755
      become: true

```
